{
 "title": "OpenSky-Dashboard",
 "time": { "from": "2020-05-31T22:00:01.000Z", "to": "2020-06-01T21:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Airframe Location Over Time",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT et_ts, icao24, lat, lon\nFROM flights TABLESAMPLE SYSTEM (5)\nWHERE icao24 IN ('738286') AND $__timeFilter(et_ts)"
    }
   ]
  },
  {
   "title": "altitude vs time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  et_ts AS \"time\",\n  baroaltitude, geoaltitude\nFROM flights\nWHERE icao24 = 'c827a6' AND $__timeFilter(et_ts)"
    }
   ]
  },
  {
   "title": "Flight Ascent in Time Window",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "rawSql": "WITH\n-- The flight_traj_time_slice CTE is clipping all the temporal columns\n-- to the user specified time-range.\nflight_traj_time_slice (icao24, callsign, time_slice_trip, time_slice_geoaltitude,\n                        time_slice_vertrate) AS\n    (SELECT icao24,\n            callsign,\n            atPeriod(trip, period '[${__from:date}, ${__to:date})'),\n            atPeriod(geoaltitude, period '[${__from:date}, ${__to:date})'),\n            atPeriod(vertrate,\n                     period '[${__from:date}, ${__to:date})')\n     FROM flight_traj_sample),\n\n-- There are 3 things happening in the flight_traj_time_slice_ascent CTE:\n-- 1. atRange: Clips the temporal data to create ranges where the vertrate\n-- was between '[1, 20]'. This vertrate means an aircraft was ascending.\n-- 2. sequenceN: Selects the first sequence from the generated sequences.\n--  This first sequence is takeoff and eliminates mid-flight ascents.\n-- 3. atPerido: Returns the period of the first sequence.\nflight_traj_time_slice_ascent(icao24, callsign, ascending_trip, ascending_geoaltitude,\n                              ascending_vertrate) AS\n    (SELECT icao24,\n            callsign,\n            atPeriod(time_slice_trip,\n                     period(sequenceN(\n                         atRange(time_slice_vertrate, floatrange '[1,20]'), 1))),\n            atPeriod(time_slice_geoaltitude,\n                     period(sequenceN(atRange(time_slice_vertrate, floatrange '[1,20]'),\n                                      1))),\n            atPeriod(time_slice_vertrate,\n                     period(sequenceN(atRange(time_slice_vertrate, floatrange '[1,20]'),\n                                      1)))\n     FROM flight_traj_time_slice),\n\n-- The final_output CTE uses unnest to unpack the temporal data into rows for\n-- visualization in Grafana. Each row will contain a latitude, longitude and the altitude\n-- and vertrate at those locations.\nfinal_output AS\n    (SELECT icao24,\n            callsign,\n            getValue(unnest(instants(ascending_geoaltitude))) AS geoaltitude,\n            getValue(unnest(instants(ascending_vertrate)))    AS vertrate,\n            ST_X(getValue(unnest(instants(ascending_trip))))  AS lon,\n            ST_Y(getValue(unnest(instants(ascending_trip))))  AS lat\n     FROM flight_traj_time_slice_ascent)\n\nSELECT *\nFROM final_output\nWHERE vertrate IS NOT NULL\n  AND geoaltitude IS NOT NULL\nORDER BY icao24;"
    }
   ]
  },
  {
   "title": "l'avion Velocity vs Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  et_ts AS \"time\",\n  velocity\nFROM flights\nWHERE icao24 = 'c827a6' AND $__timeFilter(et_ts)"
    }
   ]
  },
  {
   "title": "l'avion Velocity vs Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  et_ts AS \"time\",\n  vertrate\nFROM flights\nWHERE icao24 = 'c827a6' AND $__timeFilter(et_ts)"
    }
   ]
  },
  {
   "title": "callsign vs time",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  min(et_ts) AS \"time\", callsign\nFROM flights\nWHERE icao24 = 'c827a6'\nGROUP BY callsign"
    }
   ]
  },
  {
   "title": "Average Flight Speed",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Highest average speeds during flight\nSELECT callsign, twavg(velocity) AS average_velocity\nFROM flight_traj\nWHERE twavg(velocity) IS NOT NULL\nAND twavg(velocity) < 1500\nORDER BY twavg(velocity) desc;"
    }
   ]
  },
  {
   "title": "Number of Flights ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(callsign) AS private_flight\nFROM flight_traj\nWHERE (maxValue(velocity) IS NOT NULL -- remove flights that did not have velocity data\n    AND maxValue(velocity) <= 65) -- sport aircraft max is 140mph (65m/s)\nAND (maxValue(geoaltitude) IS NOT NULL -- remove flights that did not have altitude data\n    AND maxValue(geoaltitude) <= 5500); --18,000ft (5,500m) max for private pilot"
    },
    {
     "rawSql": "SELECT COUNT(callsign) AS commercial_flight\nFROM flight_traj\nWHERE (maxValue(velocity) IS NOT NULL \n    AND maxValue(velocity) > 65) \nAND (maxValue(geoaltitude) IS NOT NULL \n    AND maxValue(geoaltitude) > 5500); "
    }
   ]
  }
 ]
}