{
 "title": "OpenSky-Dashboard",
 "time": { "from": "2020-06-01T00:05:42.000Z", "to": "2020-06-02T03:03:42.000Z" },
 "panels": [
  {
   "title": "l'avion GPS location over time",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT et_ts, icao24, lat, lon\nFROM flights TABLESAMPLE SYSTEM (5)\nWHERE icao24 IN ('738286') AND $__timeFilter(et_ts)"
    }
   ]
  },
  {
   "title": "l'avion Velocity vs Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  et_ts AS \"time\",\n  velocity\nFROM flights\nWHERE icao24 = 'c827a6' AND $__timeFilter(et_ts)"
    }
   ]
  },
  {
   "title": "altitude vs time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  et_ts AS \"time\",\n  baroaltitude, geoaltitude\nFROM flights\nWHERE icao24 = 'c827a6' AND $__timeFilter(et_ts)"
    }
   ]
  },
  {
   "title": "l'avion Velocity vs Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  et_ts AS \"time\",\n  vertrate\nFROM flights\nWHERE icao24 = 'c827a6' AND $__timeFilter(et_ts)"
    }
   ]
  },
  {
   "title": "callsign vs time",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  min(et_ts) AS \"time\", callsign\nFROM flights\nWHERE icao24 = 'c827a6'\nGROUP BY callsign"
    }
   ]
  }
 ]
}